const CAJA1 = new Caja("Caja 1", 500, OSITO, STEAMGC, AURIS, MOUSE_GAMER, JORDANS);
const CAJA2 = new Caja("Caja 2", 2400, CAMARA, APPLE_WATCH, SMARTPHONE_SAMSUNG, IPAD, MAC);
const CAJA3 = new Caja("Caja 3", 10000, SMART, PS5, PC, OBJETO_NO_DEFINIDO, AUTO);

const CAJAS = [CAJA1, CAJA2, CAJA3];